import type { PrismaClient } from "@prisma/client";
import { Router, type NextFunction, type Request, type Response } from "express";

import { env } from "../config/env.js";
import { requireAuthentication } from "../middleware/authentication.js";
import { createPaymentService } from "../services/payments/payment-service.js";

type Database = Pick<PrismaClient, "order" | "payment"> & Partial<Pick<PrismaClient, "admin" | "notification">>;
const validId = (value: string) => /^\d+$/.test(value);

export function createPaymentsRouter({ database }: { database: Database }) {
  const service = createPaymentService({ database, keyId: env.RAZORPAY_KEY_ID });
  const start = async (request: Request<{ orderId: string }>, response: Response, next: NextFunction) => { try { const customerId = response.locals.customerId as bigint | undefined; if (customerId === undefined) { response.status(401).json({ error: "Unauthorized" }); return; } if (!validId(request.params.orderId)) { response.status(400).json({ error: "Invalid order ID" }); return; } const result = await service.startPayment(customerId, BigInt(request.params.orderId)); if (result.type === "not_found") { response.status(404).json({ error: "Order not found" }); return; } if (result.type === "cancelled") { response.status(409).json({ error: "Cancelled orders cannot be paid" }); return; } response.status(200).json(result); } catch (error) { next(error); } };
  const verify = async (request: Request<{ orderId: string }>, response: Response, next: NextFunction) => { try { const customerId = response.locals.customerId as bigint | undefined; const body = request.body as { razorpayOrderId?: unknown; razorpayPaymentId?: unknown; razorpaySignature?: unknown }; if (customerId === undefined) { response.status(401).json({ error: "Unauthorized" }); return; } if (!validId(request.params.orderId) || typeof body.razorpayOrderId !== "string" || typeof body.razorpayPaymentId !== "string" || typeof body.razorpaySignature !== "string") { response.status(400).json({ error: "Valid payment verification data is required" }); return; } const result = await service.verifyPayment(customerId, BigInt(request.params.orderId), body.razorpayOrderId, body.razorpayPaymentId, body.razorpaySignature); if (result.type === "not_found") { response.status(404).json({ error: "Order or payment not found" }); return; } if (result.type === "reference_mismatch") { response.status(409).json({ error: "Payment reference does not match this order" }); return; } if (result.type === "invalid_signature") { response.status(400).json({ error: "Invalid Razorpay payment signature" }); return; } response.status(200).json(result); } catch (error) { next(error); } };
  const completeDevelopmentPayment = async (request: Request<{ orderId: string }>, response: Response, next: NextFunction) => { try { const customerId = response.locals.customerId as bigint | undefined; if (customerId === undefined) { response.status(401).json({ error: "Unauthorized" }); return; } if (!validId(request.params.orderId)) { response.status(400).json({ error: "Invalid order ID" }); return; } const result = await service.completeDevelopmentPayment(customerId, BigInt(request.params.orderId)); if (result.type === "not_found") { response.status(404).json({ error: "Order not found" }); return; } if (result.type === "invalid_state") { response.status(409).json({ error: "Order is not awaiting payment" }); return; } response.status(200).json(result); } catch (error) { next(error); } };
  const router = Router(); router.post("/:orderId/payment", requireAuthentication, start); router.post("/:orderId/payment/verify", requireAuthentication, verify); router.post("/:orderId/payment/development/confirm", requireAuthentication, completeDevelopmentPayment); return router;
}
